# Generated by Django 4.1.6 on 2023-04-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(error_messages={'blank': 'Имя не должно быть пустым', 'max_length': 'Длина имени не должна превышать 20 символов'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(error_messages={'blank': 'Название не должно быть пустым', 'max_length': 'Длина имени не должна превышать 20 символов', 'unique': 'Такой урок уже есть. Введите другое название'}, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(error_messages={'blank': 'Имя не должно быть пустым', 'max_length': 'Длина имени не должна превышать 20 символов', 'unique': 'Имя уже занято. Введите другое'}, max_length=20, unique=True),
        ),
    ]
