# Generated by Django 4.1.6 on 2023-04-17 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customuser_alter_lesson_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(error_messages={'blank': 'Поле не должно быть пустым', 'max_length': 'Ввод не должен быть более 4 символов'}, max_length=4)),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.lesson')),
            ],
        ),
    ]
