# Generated by Django 4.1.6 on 2023-04-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(error_messages={'blank': 'Название не должно быть пустым', 'max_length': 'Длина имени не должна превышать 20 символов'}, max_length=20),
        ),
    ]
